server:
  port: 8088
  servlet:
    context-path: /platform-kafka
  undertow:
    threads:
      io: 16
      worker: 400
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: platform-kafka
  profiles:
    active: dev