platform:
  foundation:
    anonymous-rule:
      enable: false
      header: permission
      permission-uris: /send,/test
      public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCRCD2X4lP6nVTpxvmb3Sy8JyAQWHgD48ln4heWlgPZmc+/pZx7V4nGR+L55/j0wTHfSxGqlx/lrsepEL97VyG+4xDd5GQBGRz/xEM5j7AjdyKcHPAV545gn+9h0YZx6YqrR/nWlmXtKcHQWNyUu9LEmt5HTrC5dmYa3atHFB0+bwIDAQAB
      private-key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJEIPZfiU/qdVOnG+ZvdLLwnIBBYeAPjyWfiF5aWA9mZz7+lnHtXicZH4vnn+PTBMd9LEaqXH+Wux6kQv3tXIb7jEN3kZAEZHP/EQzmPsCN3Ipwc8BXnjmCf72HRhnHpiqtH+daWZe0pwdBY3JS70sSa3kdOsLl2Zhrdq0cUHT5vAgMBAAECgYAw17yehQtRMGEjZe40DpV9PBPxTUoFzVXL1XmqLhVX2BP979E2PLHag+Ut0nCmRNX95DMr5z9Hw8fb6RcDe8GSHNLY7IufXhTWJMy38oEVBqu9fWb/cEr0uRFSr5v9fnmqL89lM6v4MH9IhEtNeNLJW5IOGg78bpq1/2YUdKRVmQJBAMjXidQaP1N8u62s60XnYCRtVxe2+KtXVGKZdHAs0QZ2dV5OSo7S737XuzsXFYqt5bzboB4lyWvqfzovPGoG1NMCQQC43Owwzh/7X4Sj99UigolygOMQ1u5cTgB9VoiESjNgSZ2xypLxF+2HMh+Pa33qJNtcNqqfIDvAfdnmgJQadd51AkB0e93qcFauGzfWoOXLo0g1mFzc2jgbWAkPLqVDshqBPw8PZSUE9P4GeSSUPu01g2otQMv68DuEJXsoyeCmNdQVAkBiWof/X2t8nlE/u7fV6IWgOhqU9wVSbt2r0cJIQAIdlI0l7pVHWGezqmNINvSDAqEC6sLUbp3byBmKnZYujc+RAkAFNMUTcr1FJHnkDJ+fuH9GER99evbYuicGuiwXnyIn2exyZkczn7zMccmVGNFdTzuqdaUX1Xc6BBAjE8ihIabA
    account:
      user[0]:
        username: systemadmin
        password: $2a$10$uJ08xg9eAE.1M7Hmum4r1.L.sdjooHBYyAiK.fl9fMfwbfTrSVSXm
        permissions: all
      user[1]:
        username: test
        password: $2a$10$RzU2jR5eqkNZ/QL.rBcgnOW3z2bxZ3Z.T9u5Zf/anOfRyZW/TzfiO
        permissions: user:view,user:add
