server:
  port: 8088
  servlet:
    context-path: /platform-kafka
  undertow:
    threads:
      io: 16
      worker: 400
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: platform-kafka
  kafka:
    #bootstrap-servers: 172.26.188.1:9092,172.26.188.2:9092,172.26.188.3:9092
    bootstrap-servers: 192.168.122.171:9092
#    properties:
#      sasl:
#        mechanism: PLAIN
#        jaas:
#          config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";'
#      security:
#        protocol: SASL_PLAINTEXT
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 60000
    listener:
      log-container-config: false
      concurrency: 5
      ack-mode: manual_immediate
